[build]
target = "aarch64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.aarch64-unknown-freebsd]
linker = "/opt/homebrew/opt/llvm/bin/clang"
rustflags = [
    "-Clink-arg=--target=aarch64-pc-freebsd",
    "-Clink-arg=--sysroot=freebsd-sysroot",
    "-Clink-arg=-fuse-ld=lld",
    "-Clink-arg=-stdlib=libc++",
]
