[images.alpine-latest]
base_dir = "alpine"
docker_ref = "alpine:latest"
kernel.image_url = "https://github.com/nohajc/libkrunfw/releases/download/v6.12.62-rev1/linux-aarch64-Image-v6.12.62-anylinuxfs.tar.gz"
kernel.modules_url = "https://github.com/nohajc/libkrunfw/releases/download/v6.12.62-rev1/modules.squashfs"
os_type = "Linux"

[images."freebsd-15.0"]
base_dir = "freebsd-15.0"
iso_url = "https://download.freebsd.org/snapshots/ISO-IMAGES/15.0/FreeBSD-15.0-STABLE-arm64-aarch64-20260101-785d429c2b93-281645-bootonly.iso"
oci_url = "https://download.freebsd.org/snapshots/OCI-IMAGES/15.0-STABLE/aarch64/20260101/FreeBSD-15.0-STABLE-arm64-aarch64-container-image-20260101-785d429c2b93-281645-runtime.txz"
kernel.bundle_url = "https://github.com/nohajc/freebsd/releases/download/alfs%2F15.0/kernel.txz"
os_type = "FreeBSD"

[custom_actions.ubuntu_zfs_unlock]
description = "Mount ZFS keystore encrypted with LUKS to unlock Ubuntu system disk"
before_mount = "cryptsetup open /dev/zd0 ks0 && mkdir -p $KS && mount /dev/mapper/ks0 $KS"
after_mount = ""
before_unmount = "umount /dev/mapper/ks0 && cryptsetup close ks0"
environment = ["KS=/run/keystore/rpool"]
capture_environment = []
override_nfs_export = ""
required_os = "Linux"

[linux]
default_image = "alpine-latest"

[freebsd]
default_image = "freebsd-15.0"
